
// Handles GET (list all expenses) and POST (create a new expense)
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// GET: List all expenses via findMany
// findMany: Prisma Client method used to retrieve multiple records from a database table (model).
export async function GET() {
  const expenses = await db.expense.findMany({ orderBy: { date: 'desc' } });
  return NextResponse.json(expenses);
}

// POST: Create a new expense
export async function POST(req: NextRequest) {
  const { title, amount, date } = await req.json();
  //Expense Model: id, title, amount, date, createdAt
  // {id} is a unique identifier, auto-generated by the database(not user-editable)
  // {title, amount, date} are fields that users provide so get it from req.body
  // createdAt is auto-set by the database, so we don't need to provide it here
  const expense = await db.expense.create({
    data: { title, amount: parseFloat(amount), date: new Date(date) },
  });
  return NextResponse.json(expense, { status: 201 });
}
