
// Handles GET (list all expenses) and POST (create a new expense)
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// GET: List all expenses via findMany
// findMany: Prisma Client method used to retrieve multiple records from a database table (model).
export async function GET() {
  const expenses = await db.expense.findMany({ orderBy: { date: 'desc' } });
  return NextResponse.json(expenses);
}

// POST: Create a new expense
export async function POST(req: NextRequest) {
  const { title, amount, date } = await req.json();
  
  // SERVER-SIDE VALIDATION
  // Check if title is provided and not empty/whitespace
  if (!title || typeof title !== 'string' || title.trim().length === 0) {
    return NextResponse.json(
      { error: 'Title is required and cannot be empty' },
      { status: 400 }
    );
  }

  // Check if title is reasonable length (max 100 chars)
  if (title.length > 100) {
    return NextResponse.json(
      { error: 'Title must be 100 characters or less' },
      { status: 400 }
    );
  }

  // Check if amount is a valid number and positive
  const parsedAmount = parseFloat(amount);
  if (isNaN(parsedAmount) || parsedAmount <= 0) {
    return NextResponse.json(
      { error: 'Amount must be a positive number' },
      { status: 400 }
    );
  }

  // Check if date is valid
  const parsedDate = new Date(date);
  if (isNaN(parsedDate.getTime())) {
    return NextResponse.json(
      { error: 'Date must be a valid date' },
      { status: 400 }
    );
  }

  //Expense Model: id, title, amount, date, createdAt
  // {id} is a unique identifier, auto-generated by the database(not user-editable)
  // {title, amount, date} are fields that users provide so get it from req.body
  // createdAt is auto-set by the database, so we don't need to provide it here
  const expense = await db.expense.create({
    data: { title: title.trim(), amount: parsedAmount, date: parsedDate },
  });
  return NextResponse.json(expense, { status: 201 });
}
