import './globals.css'
import Navbar from '@/components/Navbar'

// layout.tsx — the ROOT LAYOUT for your entire app.
//
// Every page in Next.js is wrapped by this component automatically.
// Think of it as the "frame" that surrounds every page — a great place
// for things that should appear everywhere, like a navbar or footer.
//
// The `metadata` export is a special Next.js feature that sets the <title>
// and <meta> tags in your HTML <head> — no need to manage a <Head> tag yourself.
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// `children` represents whatever page the user is currently visiting.
// Next.js automatically passes the current page in as `children` here.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Every HTML page needs a root <html> element.
    // `lang="en"` helps screen readers and search engines know the language.
    <html lang="en">
      {/* <body> is where your visible page content lives.
          {children} renders whichever page the user navigated to. */}
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
